# --------------- LANGUAGE ------------- #
# Supported languages: en_US, es_ES
# Language Codes: https://learn.microsoft.com/en-us/linkedin/shared/references/reference-tables/language-codes
language: en_US # By default, this is English.
# -------------------------------------- #
